### PR TITLE
Fix duplicated ARC

### PR DESCRIPTION
**Pull request by 2sem**
Automatic Reference Counting == ARC ??
I wonder which one should be remained...

스크린샷 2023-11-21 오후 3 03 20

### CODE REVIEW

**Comment by jrasmusson** [comment]
Thank you for submitting 2sem. Sorry, where is the duplication? I don't see it. Cheers.

**Comment by 2sem** [comment]
I guess Automatic Reference Counting is ARC, isn't it? 🤔

Automatic Reference Counting
스크린샷 2023-11-26 오전 9 51 17
스크린샷 2023-11-26 오전 9 51 28

ARC
스크린샷 2023-11-26 오전 9 51 42
스크린샷 2023-11-26 오전 9 51 51

**Comment by 2sem** [comment]
or this should be fixed to? 
- ARC(Automatic Reference Counting)

**Comment by jrasmusson** [comment]
Ah yes. You are correct. I didn't even see that :) Thanks so much.

**Pull request merged**
